
### TEST 
GET http://localhost:3000/


####################################################################################

### GET CV
GET http://localhost:3000/cvs?age=21&critere=beney
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZlZGlAZ21haWwuY29tIiwidXNlcklkIjo0LCJ1c2VybmFtZSI6ImZlZGkiLCJyb2xlIjoidXNlciIsImlhdCI6MTcxNDE2NjgzNywiZXhwIjoxNzE0MjUzMjM3fQ.2ZzMW2Fb7Jq1v03wfU-Y0lgdJHPkMpCvVn9nPh9LILQ



### UPDATE CV BY ID 
PUT http://localhost:3000/cvs/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZlZGlAZ21haWwuY29tIiwidXNlcklkIjo0LCJ1c2VybmFtZSI6ImZlZGkiLCJyb2xlIjoidXNlciIsImlhdCI6MTcxNDE2NjgzNywiZXhwIjoxNzE0MjUzMjM3fQ.2ZzMW2Fb7Jq1v03wfU-Y0lgdJHPkMpCvVn9nPh9LILQ
Content-Type: application/json

{
    "job" : "constructeur"
}

### GET CV BY ID
GET http://localhost:3000/cvs/1


### DELETE CV BY ID
DELETE http://localhost:3000/cvs/1



#################################################################


### POST USER 
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "fedi",
    "email": "fedi@gmail.com" ,
    "password": "123456",
    "role": "user"
}



#########################################################################
### POST SKILL 
POST http://localhost:3000/skills
Content-Type: application/json

{
    "designation" : "peinture"
}


###########################################################################

### POST CV
POST http://localhost:3000/cvs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZlZGlAZ21haWwuY29tIiwidXNlcklkIjo0LCJ1c2VybmFtZSI6ImZlZGkiLCJyb2xlIjoidXNlciIsImlhdCI6MTcxNDE2NjgzNywiZXhwIjoxNzE0MjUzMjM3fQ.2ZzMW2Fb7Jq1v03wfU-Y0lgdJHPkMpCvVn9nPh9LILQ
Content-Type: application/json

{
    "name" : "adel",
    "firstname" : "fedi",
    "age" : 21,
    "cin": 123456,
    "job" : "testeur",
    "path" : "path test"

}

### AUTH #######################################################################""

### LOGIN USER
POST http://localhost:3000/auth/login
Content-Type: application/json

{   
    "email" : "fedi@gmail.com" , 
    "password" : "123456"
}

### SIGN UP USER
POST http://localhost:3000/auth/signup
Content-Type: application/json

{   
     "username": "fedi",
    "email": "fedi@gmail.com" ,
    "password": "123456"
}
