
### TEST 
GET http://localhost:3000/


### GET CV

GET http://localhost:3000/cvs?age=21&critere=beney
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1vaGFtZWRAZ21haWwuY29tIiwidXNlcklkIjo0LCJ1c2VybmFtZSI6ImNoYWltYWdoYXJiaSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzEzMDA5MTk0LCJleHAiOjE3MTMwOTU1OTR9.kfbELeqyJwTouMjJ__EACjit2Zxwx38qkmUa2vuha1Y

### UPDATE CV BY ID 
PUT http://localhost:3000/cvs/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1vaGFtZWRAZ21haWwuY29tIiwidXNlcklkIjo0LCJ1c2VybmFtZSI6ImNoYWltYWdoYXJiaSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzEzMDA5MTk0LCJleHAiOjE3MTMwOTU1OTR9.kfbELeqyJwTouMjJ__EACjit2Zxwx38qkmUa2vuha1Y

### POST USER 
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "fedi",
    "email": "fedi@gmail.com" ,
    "password": "123456"
}

### POST SKILL 
POST http://localhost:3000/skills
Content-Type: application/json

{
    "designation" : "lkedhb"
}


### POST CV
POST http://localhost:3000/cvs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwidXNlcklkIjo3LCJ1c2VybmFtZSI6ImN2Y3YiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTMwMzExOTgsImV4cCI6MTcxMzExNzU5OH0.oFgZLru514FXMbrYMI118oOTy-_2dGbCLya8-Vi1JYA
Content-Type: application/json

{
    "name" : "hamrouni",
    "firstname" : "lamia",
    "age" : 56,
    "cin": 123456,
    "job" : "tbiba",
    "path" : "C:/Users/lamia/Desktop"

}

### LOGIN USER
POST http://localhost:3000/auth/login
Content-Type: application/json

{   
    "email" : "test@gmail.com" , 
    "password" : "123456"
}

### SIGN UP USER
POST http://localhost:3000/auth/signup
Content-Type: application/json

{   
    "username" : "cvcv" , 
    "email" : "test@gmail.com",
    "password" : "123456"
}
